// On-screen inputs for the outputs computed in assets/wl (synced from assets/wl/manifest*.json and data/assets*).
export const CODE = {
  v2_surface: "ParametricPlot3D[{u Cos[u] (4 + Cos[v + u]), u Sin[u] (4 + Cos[v + u]), u Sin[v + u]}, {u, 0, 4 Pi}, {v, 0, 2 Pi}]",
  v5_colors: "Show[Graphics[Table[{colors[[Mod[k, 10] + 1]], EdgeForm[White], Disk[(1 + k/24) {Cos[k Pi/5.2], Sin[k Pi/5.2]}, 0.25 + k/60]}, {k, 60, 0, -1}]]]",
  v6_europe: "Graphics[{ColorData[\"SunsetColors\"][1 - Rescale[Log[CountryData[#, \"Population\"]], {11, 18.5}]], CountryData[#, \"Polygon\"]} & /@ CountryData[\"Europe\"], PlotRange -> {{-25, 45}, {34, 72}}]",
  v7_turing: "ArrayPlot[TuringMachine[{596440, 2, 3}, {1, {{}, 0}}, 240][[All, 2]]]",
  v10_globe: "GeoGraphics[{NightHemisphere[DateObject[{2014, 7, 9, 12}]], GeoPath[{champaign, #}, \"GreatCircle\"] & /@ cities}, GeoProjection -> \"Orthographic\"]",
  v10_stars: "ListPlot[StarData[EntityClass[\"Star\", \"NakedEyeStar\"], {\"EffectiveTemperature\", \"AbsoluteMagnitude\"}]]",
  v13_astro: "AstroGraphics[Point /@ orionStars, AstroCenter -> Entity[\"Star\", \"Alnilam\"], AstroRange -> Quantity[13, \"AngularDegrees\"], AstroBackground -> AstroStyling[{\"BlackSky\", \"ShowConstellations\" -> {Entity[\"Constellation\", \"Orion\"]}}]]",
  v12_molecule: "MoleculePlot3D[Molecule[\"caffeine\"]]",
  v4_rule30: "Show[Graphics[Raster[1 - Reverse[CellularAutomaton[30, {{1}, 0}, 160]]]]]",
  v12_system: "SystemModelSimulate[\"Modelica.Mechanics.MultiBody.Examples.Elementary.DoublePendulum\", 6]",
  x_parallel: "ParallelTable[julia[x + I y], {y, 0.95, -0.95, -0.0064}, {x, -1.6, 1.6, 0.0067}]",
  v8_graph: "Graph[UndirectedEdge @@@ borders, VertexLabels -> Automatic]",
  x_graph: "Graph[Flatten[Thread[UndirectedEdge[#, WolframLanguageData[#, \"RelatedSymbols\"]]] & /@ seeds]]",
  x_fireballs: "GeoBubbleChart[ResourceData[\"Fireballs and Bolides\"][All, #Coordinates -> #TotalRadiatedEnergy &]]",
  x_compile: "cf = FunctionCompile[Function[Typed[n, \"MachineInteger\"], Module[{s = 0., i = 1}, While[i <= n, s += Sin[N[i]]^2; i++]; s]]]",
  x_tree: "ExpressionTree[Hold[Manipulate[Plot[Sin[a x], {x, 0, 2 Pi}], {a, 1, 5}]]]",
  x_quantum: "QuantumCircuitOperator[{\"H\", \"CNOT\" -> {1, 2}, \"CNOT\" -> {2, 3}}][\"Diagram\"]",
};
